/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 191.254, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[146.027, 210.859, 148.609]}>
          <mesh geometry={nodes.Roundcube_Red_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Roundcube_Gray_0.geometry} material={materials.Gray} />
        </group>
        <group position={[0, 398.501, 10.897]} rotation={[-Math.PI / 2, 0, 0]} scale={[116.982, 184.039, 111.189]}>
          <mesh geometry={nodes.Roundcube001_Red_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Roundcube001_Gray_0.geometry} material={materials.Gray} />
        </group>
        <group position={[0, 156.376, -286.206]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[134.771, 88.8, 109.239]}>
          <mesh geometry={nodes.Roundcube002_Red_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Roundcube002_Gray_0.geometry} material={materials.Gray} />
        </group>
        <group position={[-119.965, 109.164, -308.368]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={3.027}>
          <mesh geometry={nodes.Circle001_Black_0.geometry} material={materials.Black} />
          <mesh geometry={nodes.Circle001_Gray_0.geometry} material={materials.Gray} />
        </group>
        <group position={[3.43, 393.997, 196.567]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[9.435, 41.805, 54.645]}>
          <mesh geometry={nodes.Roundcube005_DrownWindow_0.geometry} material={materials.DrownWindow} />
          <mesh geometry={nodes.Roundcube005_Window_0.geometry} material={materials.Window} />
        </group>
        <group position={[-122.055, 393.997, 68.983]} rotation={[-Math.PI / 2, 0, 0]} scale={[9.435, 41.805, 54.645]}>
          <mesh geometry={nodes.Roundcube004_DrownWindow_0.geometry} material={materials.DrownWindow} />
          <mesh geometry={nodes.Roundcube004_Window_0.geometry} material={materials.Window} />
        </group>
        <group position={[-122.055, 393.997, -43.861]} rotation={[-Math.PI / 2, 0, 0]} scale={[9.435, 41.805, 54.645]}>
          <mesh geometry={nodes.Roundcube006_DrownWindow_0.geometry} material={materials.DrownWindow} />
          <mesh geometry={nodes.Roundcube006_Window_0.geometry} material={materials.Window} />
        </group>
        <group position={[-149.75, 168.203, -68.399]} rotation={[-Math.PI / 2, 0, 0]} scale={[9.435, 41.805, 54.645]}>
          <mesh geometry={nodes.Roundcube007_DrownWindow_0.geometry} material={materials.DrownWindow} />
          <mesh geometry={nodes.Roundcube007_Window_0.geometry} material={materials.Window} />
        </group>
        <group position={[152.244, 176.255, -43.861]} rotation={[-Math.PI / 2, 0, -3.141]} scale={[9.435, 41.805, 54.645]}>
          <mesh geometry={nodes.Roundcube036_DrownWindow_0.geometry} material={materials.DrownWindow} />
          <mesh geometry={nodes.Roundcube036_Window_0.geometry} material={materials.Window} />
        </group>
        <group position={[152.244, 176.255, 68.983]} rotation={[-Math.PI / 2, 0, -3.141]} scale={[9.435, 41.805, 54.645]}>
          <mesh geometry={nodes.Roundcube035_DrownWindow_0.geometry} material={materials.DrownWindow} />
          <mesh geometry={nodes.Roundcube035_Window_0.geometry} material={materials.Window} />
        </group>
        <group position={[121.688, 390.848, 11.884]} rotation={[-Math.PI / 2, 0, -3.141]} scale={[9.435, 41.805, 54.645]}>
          <mesh geometry={nodes.Roundcube037_DrownWindow_0.geometry} material={materials.DrownWindow} />
          <mesh geometry={nodes.Roundcube037_Window_0.geometry} material={materials.Window} />
        </group>
        <mesh geometry={nodes.Roundcube003_Gray_0.geometry} material={materials.Gray} position={[-147.605, 162.692, 94.719]} rotation={[-Math.PI / 2, 0, 0]} scale={[9.435, 41.805, 93.478]} />
        <mesh geometry={nodes.Sphere_Red_0.geometry} material={materials.material} position={[-154.7, 152.077, 67.543]} rotation={[-Math.PI / 2, 0, 0]} scale={7.872} />
        <mesh geometry={nodes.Roundcube008_Gray_0.geometry} material={materials.Gray} position={[-156.829, 59.602, 93.55]} rotation={[-Math.PI / 2, 0, 0]} scale={[18.287, 45.937, 18.287]} />
        <mesh geometry={nodes.Roundcube009_Gray_0.geometry} material={materials.Gray} position={[0, 55.024, -109.527]} rotation={[-Math.PI / 2, 0, 0]} scale={[164.04, 332.745, 12.361]} />
        <mesh geometry={nodes.Roundcube010_Ground_0.geometry} material={materials.Ground} position={[89.081, 24.961, -199.364]} rotation={[Math.PI / 2, 0, 0]} scale={[-377.188, 501.783, 22.478]} />
        <mesh geometry={nodes.Cylinder_Gray_0.geometry} material={materials.Gray} position={[-234.818, 51.143, 92.975]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.353, 3.353, 16.799]} />
        <mesh geometry={nodes.Roundcube013_Material036_0.geometry} material={materials['Material.036']} position={[-9.241, 104.518, 267.955]} rotation={[Math.PI / 2, 0, 0]} scale={[125.733, 9.896, 8.412]} />
        <mesh geometry={nodes.Roundcube011_Material036_0.geometry} material={materials['Material.036']} position={[-9.241, 66.409, 267.955]} rotation={[Math.PI / 2, 0, 0]} scale={[125.733, 9.896, 8.412]} />
        <mesh geometry={nodes.Roundcube012_Material017_0.geometry} material={materials['Material.017']} position={[-124.775, 83.856, 275.962]} rotation={[Math.PI / 2, 0, 0]} scale={[15.887, 5.673, 41.793]} />
        <mesh geometry={nodes.Roundcube014_Material017_0.geometry} material={materials['Material.017']} position={[-76.438, 83.856, 275.962]} rotation={[Math.PI / 2, 0, 0]} scale={[15.887, 5.673, 41.793]} />
        <mesh geometry={nodes.Roundcube015_Material017_0.geometry} material={materials['Material.017']} position={[-28.953, 83.856, 275.962]} rotation={[Math.PI / 2, 0, 0]} scale={[15.887, 5.673, 41.793]} />
        <mesh geometry={nodes.Roundcube018_Material017_0.geometry} material={materials['Material.017']} position={[16.776, 83.856, 275.962]} rotation={[Math.PI / 2, 0, 0]} scale={[15.887, 5.673, 41.793]} />
        <mesh geometry={nodes.Roundcube017_Material017_0.geometry} material={materials['Material.017']} position={[65.114, 83.856, 275.962]} rotation={[Math.PI / 2, 0, 0]} scale={[15.887, 5.673, 41.793]} />
        <mesh geometry={nodes.Roundcube016_Material017_0.geometry} material={materials['Material.017']} position={[112.599, 83.856, 275.962]} rotation={[Math.PI / 2, 0, 0]} scale={[15.887, 5.673, 41.793]} />
        <mesh geometry={nodes.Roundcube026_Material036_0.geometry} material={materials['Material.036']} position={[408.571, 66.409, 100.86]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[125.733, 9.896, 8.412]} />
        <mesh geometry={nodes.Roundcube025_Material017_0.geometry} material={materials['Material.017']} position={[416.579, 83.856, 216.395]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[15.887, 5.673, 41.793]} />
        <mesh geometry={nodes.Roundcube024_Material036_0.geometry} material={materials['Material.036']} position={[408.571, 104.518, 100.86]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[125.733, 9.896, 8.412]} />
        <mesh geometry={nodes.Roundcube023_Material017_0.geometry} material={materials['Material.017']} position={[416.579, 83.856, 168.057]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[15.887, 5.673, 41.793]} />
        <mesh geometry={nodes.Roundcube022_Material017_0.geometry} material={materials['Material.017']} position={[416.579, 83.856, 120.572]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[15.887, 5.673, 41.793]} />
        <mesh geometry={nodes.Roundcube021_Material017_0.geometry} material={materials['Material.017']} position={[416.579, 83.856, -20.979]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[15.887, 5.673, 41.793]} />
        <mesh geometry={nodes.Roundcube020_Material017_0.geometry} material={materials['Material.017']} position={[416.579, 83.856, 26.506]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[15.887, 5.673, 41.793]} />
        <mesh geometry={nodes.Roundcube019_Material017_0.geometry} material={materials['Material.017']} position={[416.579, 83.856, 74.843]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[15.887, 5.673, 41.793]} />
        <mesh geometry={nodes.Roundcube034_Material017_0.geometry} material={materials['Material.017']} position={[416.579, 83.856, -468.118]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[15.887, 5.673, 41.793]} />
        <mesh geometry={nodes.Roundcube033_Material017_0.geometry} material={materials['Material.017']} position={[416.579, 83.856, -516.456]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[15.887, 5.673, 41.793]} />
        <mesh geometry={nodes.Roundcube032_Material017_0.geometry} material={materials['Material.017']} position={[416.579, 83.856, -563.941]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[15.887, 5.673, 41.793]} />
        <mesh geometry={nodes.Roundcube031_Material017_0.geometry} material={materials['Material.017']} position={[416.579, 83.856, -422.389]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[15.887, 5.673, 41.793]} />
        <mesh geometry={nodes.Roundcube030_Material017_0.geometry} material={materials['Material.017']} position={[416.579, 83.856, -374.904]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[15.887, 5.673, 41.793]} />
        <mesh geometry={nodes.Roundcube029_Material036_0.geometry} material={materials['Material.036']} position={[408.571, 104.518, -442.101]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[125.733, 9.896, 8.412]} />
        <mesh geometry={nodes.Roundcube028_Material017_0.geometry} material={materials['Material.017']} position={[416.579, 83.856, -326.566]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[15.887, 5.673, 41.793]} />
        <mesh geometry={nodes.Roundcube027_Material036_0.geometry} material={materials['Material.036']} position={[408.571, 66.409, -442.101]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[125.733, 9.896, 8.412]} />
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
